### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by dunk8888** [PaulStoffregen/Arduino-1.8.2-Teensyduino#1]
Hi,sorry for asking this hear i know its for issues bugs etc,but what do i do with this arduino ide file structure,there is no exe for the arduino ide,does this need compiling or do the files just need putting into an existing arduino ide?Not sure how to use this.i just want to add teensyduino to my ide.
Thanks

**Comment by PaulStoffregen** [comment]
Follow the steps documented here:

https://www.pjrc.com/teensy/td_download.html
